### ISSUE TITLE
Restart State

### ISSUE THREAD

**Issue by ManoR88** [gtmora200/ZExplosionField#2]
After using

explosionField.explode(view, true);//this method with parameter true return view to original state

view becomes visible but not able to click again

if explosionField.setClickable(true); is used

view becomes visible but can't able to click anything in app

kindly sort this :)

**Comment by gtmora200** [comment]
Clone repository on local pc. See app project, i solve this problem with a listener and reassigned listener.

Original state don’t includes events. 

Please try it!!
